/**
 * @description  : Constants
 * @author       : Ivo Rocha
 **/
public class Constants {
	public final static String LEAD_STATUS_NEW = 'New';
	public final static String LEAD_STATUS_WORKING = 'Working';
	public final static String LEAD_STATUS_QUALIFIED = 'Qualified';
	public final static String LEAD_STATUS_UNQUALIFIED = 'Unqualified';
	public final static String LEAD_STATUS_CONVERTED = 'Converted';
	public final static String LEAD_STATUS_EXISTING_PATIENT = 'Existing Patient';

	private Constants() {
	}
}
